sudo: false
script:
  - npm install
env:
  - VALIDATORS=tv4
  - VALIDATORS=zschema
matrix:
  allow_failures:
    - env: VALIDATORS=tv4
install:
  - rm -rf ~/.nvm
  - mkdir -p ~/.nvm
  - curl -L https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh
  - source ~/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
script:
  - npm install
  - node node_modules/mdv/mdv versions/3.*.md
  - scripts/md2html/build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: pretty # change to master
  local_dir: deploy
