name: Automerge all-contributors PRs

# Author: @MikeRalphson

on:
  workflow_dispatch: {}
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  #check_suite:
  #  types:
  #    - completed
  status: {}
  
jobs:

  automerge:
    runs-on: ubuntu-latest
    #if: github.event.pull_request.draft == false
    steps:
      - name: Automerging
        uses: pascalgn/automerge-action@v0.14.2
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FILTER_AUTHOR: "allcontributors"
